version: "3"

services:
    api:
        build: ./api/
        container_name: api_container
        volumes:
            - ./api/api:/workspace
        ports:
            - 8000:8000
        working_dir: /workspace
        tty: true
        depends_on:
            db:
                condition: service_healthy
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    db:
        image: mysql
        container_name: mysql_container
        restart: always
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=web_db
            - TZ=Asia/Tokyo
        volumes:
            - ./db/mysql/:/var/lib/mysql
        healthcheck:
            test: mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD

    phpmyadmin:
        container_name: phpmyadmin_container
        image: phpmyadmin
        depends_on:
            - db
        ports:
            - "80:80"
        environment:
            - PMA_HOST=db
            - PMA_PASSWORD=password
            - PMA_USER=root
        tty: true
        restart: always
