FROM python:latest

RUN pip3 install uvicorn
RUN pip3 install fastapi
RUN pip3 install SQLAlchemy
RUN pip3 install mysqlclient
RUN pip3 install python-ulid
RUN pip3 install requests
RUN pip3 install python-multipart
RUN pip3 install python-jose
RUN pip3 install passlib